#!/usr/bin/env bash

CUBLAS_WORKSPACE_CONFIG=:4096:8 python train_grid.py --config_path configs/mnist/final_2400.yml

CUBLAS_WORKSPACE_CONFIG=:4096:8 python finetune.py --config_path configs/mnist/final_2400.yml