strategy_args:
  num_epochs: 100
  strategy_name: krum_opt
  krum_attack: bisect_opt_alpha
  krum_dynamic_radius_scaling: 1.

aggregator_args:
  aggregator_name: krum
  krum_type: top
  m_krum: 1
  fine_tune: 2400
  fine_tune_epochs: 100
  fine_tune_clip: -1

backdoor_args:
  attack_type: badnets
  backdoor_name: single_pixel
  k: 0.2
  refresh_backdoor: False
  trigger_type: single_label
  target_class: 0

client_args:
  model_name: lenet
  optimizer: sgd
  num_clients: 20
  subset_size: 20
  malicious_lr: 0.02
  benign_lr: 0.02
  benign_epoch: 1
  malicious_epoch: 3
  num_malicious_clients: 1

env_args:
  save_path: ./saved_models/mnist/final_2400
  seed: 0
  batch_size: 64
  dataset: mnist
  use_tf32: False
  eval_batch_size: 10000
