strategy_args:
  num_epochs: 100
  strategy_name: krum_opt
  krum_attack: dynamic_alpha
  krum_dynamic_radius_scaling: 1.5

aggregator_args:
  aggregator_name: krum
  krum_type: top
  m_krum: 1
  fine_tune: 2000
  fine_tune_epochs: 100
  fine_tune_clip: -1

backdoor_args:
  attack_type: static
  backdoor_name: blended
  k: 0.2
  refresh_backdoor: False
  trigger_type: single_label
  target_class: 0

client_args:
  model_name: resnet18
  optimizer: sgd
  num_clients: 20
  subset_size: 20
  benign_epoch: 1
  malicious_epoch: 1

env_args:
  save_path: ./saved_models/lr_0_01_ft_2000_k_0_2/blended_krum_opt_fine_tune/
  seed: 0
  batch_size: 64
  dataset: cifar10
  use_tf32: False
  eval_batch_size: 10000
