strategy_args:
  num_epochs: 100
  strategy_name: norm_opt

aggregator_args:
  aggregator_name: norm
  norm_type: clip
  norm_bound: 5
  fine_tune: 2000
  fine_tune_epochs: 1
  fine_tune_clip: -1

backdoor_args:
  attack_type: badnets
  backdoor_name: single_pixel
  k: 0.2
  refresh_backdoor: False
  trigger_type: single_label
  target_class: 0

client_args:
  model_name: resnet18
  optimizer: sgd
  num_clients: 20
  subset_size: 20
  num_malicious_clients: 8
  benign_lr: 0.01
  benign_epoch: 1
  malicious_lr: 0.01
  malicious_epoch: 1

env_args:
  save_path: ./saved_models/paper_figures/figure_2/
  seed: 0
  batch_size: 64
  dataset: cifar10
  use_tf32: False
  eval_batch_size: 10000
